# Site settings
title: South Asia L.E.A.R.N.
description: L.E.A.R.N. aims to make the world a better place by giving greater opportunity for leadership and education development to the world.  We believe every person should have the opportunity to develop to their full potential.

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1037ac
  secondary: fec503  
  secondary-dark: 333333

# Build settings
markdown: kramdown
permalink: pretty